FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /weather-backend-app

COPY requirements.txt /weather-backend-app/

RUN pip install -U pip && pip install -r requirements.txt

COPY . /weather-backend-app/
