# Generated by Django 5.2.4 on 2025-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("air_frost", "Air Frost"),
                            ("raindays", "Rain Days ≥1mm"),
                            ("rainfall", "Rainfall"),
                            ("sunshine", "Sunshine"),
                            ("tmean", "Mean Temperature"),
                            ("tmin", "Minimum Temperature"),
                            ("tmax", "Maximum Temperature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("jan", models.FloatField(blank=True, null=True)),
                ("feb", models.FloatField(blank=True, null=True)),
                ("mar", models.FloatField(blank=True, null=True)),
                ("apr", models.FloatField(blank=True, null=True)),
                ("may", models.FloatField(blank=True, null=True)),
                ("jun", models.FloatField(blank=True, null=True)),
                ("jul", models.FloatField(blank=True, null=True)),
                ("aug", models.FloatField(blank=True, null=True)),
                ("sep", models.FloatField(blank=True, null=True)),
                ("oct", models.FloatField(blank=True, null=True)),
                ("nov", models.FloatField(blank=True, null=True)),
                ("dec", models.FloatField(blank=True, null=True)),
                ("win", models.FloatField(blank=True, null=True)),
                ("spr", models.FloatField(blank=True, null=True)),
                ("sum", models.FloatField(blank=True, null=True)),
                ("aut", models.FloatField(blank=True, null=True)),
                ("ann", models.FloatField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "year"), name="unique_dataset_year"
                    )
                ],
            },
        ),
    ]
