# Generated by Django 5.2.4 on 2025-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climatemonthly",
            options={
                "verbose_name": "Climate Monthly",
                "verbose_name_plural": "Climate Monthlies",
            },
        ),
        migrations.AlterModelOptions(
            name="climateparameter",
            options={
                "verbose_name": "Climate Parameter",
                "verbose_name_plural": "Climate Parameters",
            },
        ),
        migrations.AlterModelOptions(
            name="climateregion",
            options={
                "verbose_name": "Climate Region",
                "verbose_name_plural": "Climate Regions",
            },
        ),
        migrations.AlterModelOptions(
            name="climateseason",
            options={
                "verbose_name": "Climate Season",
                "verbose_name_plural": "Climate Seasons",
            },
        ),
        migrations.AlterField(
            model_name="climateregion",
            name="region",
            field=models.CharField(
                choices=[
                    ("UK", "UK"),
                    ("England", "England"),
                    ("Wales", "Wales"),
                    ("Scotland", "Scotland"),
                    ("Northern_Ireland", "Northern Ireland"),
                    ("England_and_Wales", "England and Wales"),
                    ("England_N", "England North"),
                    ("England_S", "England South"),
                    ("Scotland_N", "Scotland North"),
                    ("Scotland_E", "Scotland East"),
                    ("Scotland_W", "Scotland West"),
                    ("England_E_and_NE", "England East and NE"),
                    ("England_NW_and_N_Wales", "England NW and North Wales"),
                    ("Midlands", "Midlands"),
                    ("East_Anglia", "East Anglia"),
                    ("England_SW_and_S_Wales", "England SW and South Wales"),
                    ("England_SE_and_Central_S", "England SE and Central South"),
                ],
                help_text="Select the geographical region.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
