# Generated by Django 5.2.4 on 2025-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0002_alter_climatemonthly_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climateparameter",
            name="parameter",
            field=models.CharField(
                choices=[
                    ("air_frost", "Air Frost"),
                    ("raindays", "Rain Days ≥1mm"),
                    ("rainfall", "Rainfall"),
                    ("sunshine", "Sunshine"),
                    ("tmean", "Mean Temperature"),
                    ("tmin", "Minimum Temperature"),
                    ("tmax", "Maximum Temperature"),
                ],
                help_text="The type of climate parameter.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
