# Generated by Django 5.2.4 on 2025-09-27 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0003_alter_climateparameter_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatemonthly",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                help_text="The month of the data, from 1 (January) to 12 (December).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="climaterecord",
            name="year",
            field=models.PositiveIntegerField(
                help_text="The year this climate data refers to.",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
