# Generated by Django 5.2.4 on 2025-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0003_remove_climaterecord_unique_dataset_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climaterecord",
            name="region",
            field=models.CharField(
                choices=[
                    ("UK", "UK"),
                    ("England", "England"),
                    ("Wales", "Wales"),
                    ("Scotland", "Scotland"),
                    ("Northern_Ireland", "Northern Ireland"),
                    ("England_and_Wales", "England and Wales"),
                    ("England_N", "England North"),
                    ("England_S", "England South"),
                    ("Scotland_N", "Scotland North"),
                    ("Scotland_E", "Scotland East"),
                    ("Scotland_W", "Scotland West"),
                    ("England_E_and_NE", "England East and NE"),
                    ("England_NW_and_N_Wales", "England NW and North Wales"),
                    ("Midlands", "Midlands"),
                    ("East_Anglia", "East Anglia"),
                    ("England_SW_and_S_Wales", "England SW and South Wales"),
                    ("England_SE_and_Central_S", "England SE and Central South"),
                ],
                max_length=50,
            ),
        ),
    ]
