# Generated by Django 5.2.4 on 2025-10-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0004_alter_climatemonthly_month_alter_climaterecord_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateSeasonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("win", "Winter"),
                            ("spr", "Spring"),
                            ("sum", "Summer"),
                            ("aut", "Autumn"),
                            ("ann", "Annual"),
                        ],
                        help_text="Season for the climate data",
                        max_length=3,
                    ),
                ),
                ("data", models.FloatField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_data",
                        to="climate.climaterecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Season",
                "verbose_name_plural": "Climate Seasons",
            },
        ),
        migrations.DeleteModel(
            name="ClimateSeason",
        ),
        migrations.AddIndex(
            model_name="climateseasonal",
            index=models.Index(
                fields=["record", "season"], name="climate_cli_record__d011ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="climateseasonal",
            constraint=models.UniqueConstraint(
                fields=("season", "record"), name="unique_season_record"
            ),
        ),
    ]
