# Generated by Django 5.2.4 on 2025-10-15 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0005_climateseasonal_delete_climateseason_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climateseasonal",
            options={
                "verbose_name": "Climate Seasonal",
                "verbose_name_plural": "Climate Seasonals",
            },
        ),
        migrations.AlterField(
            model_name="climaterecord",
            name="year",
            field=models.PositiveIntegerField(
                help_text="The year this climate data refers to.",
                validators=[
                    django.core.validators.MinValueValidator(1600),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
