# Generated by Django 5.2.4 on 2025-10-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0006_alter_climateseasonal_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climatemonthly",
            options={},
        ),
        migrations.AlterModelOptions(
            name="climateparameter",
            options={},
        ),
        migrations.AlterModelOptions(
            name="climaterecord",
            options={},
        ),
        migrations.AlterModelOptions(
            name="climateregion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="climateseasonal",
            options={},
        ),
    ]
