# Generated by Django 5.2.4 on 2025-10-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0007_alter_climatemonthly_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="climatemonthly",
            name="unique_record_month",
        ),
        migrations.RemoveConstraint(
            model_name="climaterecord",
            name="unique_parameter_region_year",
        ),
        migrations.RemoveConstraint(
            model_name="climateseasonal",
            name="unique_season_record",
        ),
        migrations.AlterUniqueTogether(
            name="climatemonthly",
            unique_together={("record", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="climaterecord",
            unique_together={("parameter", "region", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="climateseasonal",
            unique_together={("season", "record")},
        ),
    ]
