# Generated by Django 5.2.4 on 2025-10-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0008_remove_climatemonthly_unique_record_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatemonthly",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="climate.climaterecord"
            ),
        ),
        migrations.AlterField(
            model_name="climateseasonal",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="climate.climaterecord"
            ),
        ),
    ]
