# Generated by Django 5.2.4 on 2025-10-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0009_alter_climatemonthly_record_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climaterecord",
            options={"ordering": ["-year"]},
        ),
    ]
